-- The game's logical resolution — the ONE place it is written down.
-- conf.lua reads it to size the real window; systems read it to place,
-- bounce, and clamp things; the editor (lesson 04.5) reads it to size
-- the canvas the game renders into.
--
-- Until this lesson, systems asked `love.graphics.getWidth()` instead,
-- and it happened to return the same 960 — a hidden assumption that the
-- window IS the game. The editor broke it on purpose: its window is
-- 1440 wide while the game stays 960. The window belongs to the
-- platform; the RESOLUTION belongs to the game. (Unity draws the same
-- line: `Screen.width` in game code reports the game's resolution, not
-- the editor window's.)
--
-- 640×400 is the PC-98 resolution Princess Maker and Tokimeki Memorial
-- were drawn for (see docs/GDD.md §10.5). For now the window matches it
-- 1:1; ×2 integer scaling arrives with the presentation lesson.
return { w = 640, h = 400 }
